export {default as Home} from "./Home"
export {default as About} from "./About"
export {default as Resume} from "./Resume"
export {default as MyProjects} from "./MyProjects"
export {default as Comment} from "./Comment"